### ISSUE TITLE
Driver for circuitpython / micropython

### ISSUE THREAD

**Issue by Seistea** [sciosense/ENS160_driver#2]
Hi all,
is there any implementation of the ENS160 driver for circuitpython/ micropython planned?

Thanks in advance!

**Comment by sctv** [comment]
There is a python example at 
https://github.com/DFRobot/DFRobot_ENS160/tree/main/python/raspberrypi

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit_CircuitPython_ENS160
