### ISSUE TITLE
ENS160:: requires instantiator that uses predefined Wire() connection

### ISSUE THREAD

**Issue by bryn51** [sciosense/ENS160_driver#4]
When using the device in a system that has I2C wire previously defined; then an instantiator [ begin() ] that uses that existing definition instead of trying to define its own wire port.

The use case: I have 'SmartCitizen'  SAMD21G system that has two I2C channels defined; one of which has I2C Mux (TCA9458A) connected; and the ENS160 + ENS210 are connected to one channel.
The operation mode calls for switching one the appropriate Mux Channel before communicating with the ENS devices.
It is simply unnecessary for the ENS160 library to carry on making its own wire definition.  I do not want to have to support that.
Its not the business of the library that supports VOC measurement to manage I2C.

Therefore my request is to add support for the predefined Wire such as begin( uint8_t deviceAddress, TwoWire *Wire).

I will add such function to my copy of the library; but would like you to add it to the master.

**Comment by bryn51** [comment]
SCIOSENSE have not responded to this issue

**Comment by rishi-a** [comment]
@bryn51 did you find any resolution to your issue? Did you migrate to any other library? asking since I happen to have a similar query.

**Comment by bryn51** [comment]
Well the issue was resolved by making a slight adjustment to the code.  I moved on, and there has been no response from sciosense.

**Comment by webseitz** [comment]
We apologize for not responding on time. However, please check-out our new ENS16x library which solves this issue: https://github.com/sciosense/ens16x-arduino.
