### ISSUE TITLE
why offset measured values?

### ISSUE THREAD

**Issue by aldr3i** [sciosense/ENS160_driver#6]
in the example code `ens160_dev_shield.ino`, why is there an offset of 500 for the tVOC readings and 400 for the eCO2? 
```
if (new_TVOC < 500) new_TVOC = 0; 
  else if (new_TVOC > 5000) new_TVOC = 5000;
  else new_TVOC = new_TVOC - 500;

  new_eCO2 = (uint16_t)ens160.geteCO2();
  if (new_eCO2 < 400) new_eCO2 = 400;
  else if (new_eCO2 > 5000) new_eCO2 = 5000;
```

**Comment by webseitz** [comment]
Sorry for our late answer. The above code is only for the RGB LED control. Please use `ens160.getTVOC()` and `ens160.geteCO2()` to get the sensor readings.
