### ISSUE TITLE
Sensor Outputs 0 in OPMODE"Normal operation"

### ISSUE THREAD

**Issue by Yutao-Jin** [sciosense/ENS160_driver#8]
I'm using a micropython library, the ens160 outputs good data when first powered up but after the initial start-up the when the VALIDITY FLAG goes to 0, which meas normal operation it just outputs 0 for all data.

![](https://user-images.githubusercontent.com/71048891/231310863-828d2c8b-2f2a-47da-9cd0-d62e41cc9da1.png)

**Comment by flisboac** [comment]
I also observed the same with a new ENS160. I'm able to communicate and obtain part ID and firmware version  information, but status is always 0 (meaning no errors, and normal operation), and all measurement registers return 0 as well.

Before the initial start-up (1 hour or so), I could see some values being returned from data registers, but not anymore.

**Comment by flisboac** [comment]
Well, I think I found out why it was failing to read values.

It's not enough to set the operation mode (STANDARD, or otherwise) once, you actually need to set it for every measurement cycle.

Example: need to read AQI, TVOC and eCO2? Set the operation mode to STANDARD, and poll the STATUS register. Once the flag for new data (NEWDAT and NEWGPR) is set, you can proceed to read all those registers at once. Once the measurements are read, the STATUS flag is all cleared (not only the NEW flags, but also the OPMODE one (bit 7)). To trigger a new measurement cycle, you need to set the OPMODE again.

**Comment by patryk02** [comment]
Once an OPMODE is set, the ens160 stays in thes OPMODE.
If an OPMODE was set but bit 7 in the  STATUS register is still '0', it
means something went wrong while initializing the OPMODE
Usually such operation is observed, when the VDD or VDDIO drops below the
lower limit.
The minimum and maximum voltage levels are described in the datasheet (e.g.
VDD has to stay above 1.71V).

**Comment by flisboac** [comment]
That could be possible. I'll verify the voltage as soon as I'm home again.

In my experience, I did exactly that. From a software reset, the first measurement would be performed; I could see that STATUS bit 7 would be set, and validity would always indicate initial start-up. But from then on, the device would never perform further measurements, and the whole STATUS register would be either 0, or 3 (and in both cases, DATA registers would only return 0).

In any case, what is the frequency of measurements when STANDARD mode is set? Is there any way to configure it?

**Comment by flisboac** [comment]
@patryk02 just checked, VDD on my sensor is at 1.81V, this is within specification. However, VDDIO is at 4.082V, which is above the maximum, unfortunately. Would that explain this behaviour?

In any case, I think I'll just buy a different module.

**Comment by EvoSparqz** [comment]
@flisboac I have the same issue, I can read the device ID, firmware revision etc, but I only see a status of 0, and sensor values of 0.  VDD is 1.79v and VDDIO is 3.32v

My firmware revision is 5.4.6 if anyone has anything different?

**Comment by flisboac** [comment]
Mine is also 5.4.6. But now, not even my workaround is working. I'm back to all-zero values (including STATUS).

**Comment by patryk02** [comment]
Hi,
Please check the voltage  levels with an oscilloscope.
When the ENS160 is starting in an OPMODE, the sensor needs for a short
period of time a lot of current.
In the datasheet (Table 3: Electrical characteristics, page 7), you will
find a parameter called "Peak Supply Current" .
The parameter tells you that the sensor is consuming nearly 80mA of current
during the initialization of the OPMODE.
This can cause a short voltage glitch on the VDD line below 1.71V.
If this happens, then the sensor goes into a brown out state and resets
itself.

To prevent such a behaviour, it is necessary to solder a capacitor as near
to the  VDD pin as possible.
A 10uF ceramic capacitor should be fine.

BR
Patryk

**Comment by EvoSparqz** [comment]
@flisboac I got a prompt response, very similar to @patryk02, so I dusted off the scope and although I could not produce a waveform to suggest such, there is a min/max voltage recorded and indeed the 1.8V supply line drops to 1.57V which is enough to reset the sensor.  I'll see if I can tag on an additional ceramic capacitor, either the existing one is not large enough or is faulty.

**Comment by Yutao-Jin** [comment]
> @flisboac I got a prompt response, very similar to @patryk02, so I dusted off the scope and although I could not produce a waveform to suggest such, there is a min/max voltage recorded and indeed the 1.8V supply line drops to 1.57V which is enough to reset the sensor. I'll see if I can tag on an additional ceramic capacitor, either the existing one is not large enough or is faulty.

But somehow I use the same sensor breakout with arduino library, it works without giving me 0 readings in regular opmode

**Comment by flisboac** [comment]
@EvoSparqz @patryk02 I don't have an oscilloscope, but I had some THT tantalum capacitors laying around. I just did some modifications on my sensor module to add a 47uF cap in parallel with the 1.8V rail, and so far, it seems to be working. Indeed, changing the opmode constantly is not necessary. Right now it's on the Initial Startup state, and I hope that in the next few hours it will transition to the "Operating OK" mode.

Upon closer inspection, this module I bought uses a combination of 662K and 65K5 voltage regulators to output 3.3V and 1.8V respectively from a single 5V rail. They both have output capacitors on them, but also some decoupling ones near the sensor. However, the capacitance must indeed be rather low, and not only that, the 3.3V rail is at 4.0V currently, so I guess the 662K is somewhat defective; despite that not having much effect for now, long-term, I guess this may damage the sensor. So here is my advice for everyone: resist the urge to buy combo modules, and more specifically, do NOT buy the ENS160 + AHT20 module! :D

**Comment by flisboac** [comment]
My ENS160 is still running on "Initial Startup."

@patryk02 not necessarily regarding this issue, but I have some questions regarding the ENS160, I'd be glad if you could  answer any of them:

1. Is there any way to force ENS160 to run an "Initial Start-up" again?
1. Does the IC stop measuring until the data registers are read? If so, what if I read only some of them, would it still trigger a new measurement?
1. Is there any way to change the rate at which measurements are taken, when in STANDARD or CUSTOM mode? (From the "Immediate response time," I suppose it takes a measurement at least once a second, but I'm not sure)

**Comment by EvoSparqz** [comment]
@flisboac I believe we have the same module.  I have changed VIN from 5V to 3.3V and that has fixed the I2C levels.  I recycled a ceramic SMD capacitor and added that to the 1.8V circuit, that made no difference to the voltage drop, I believe I have access to a tantalum capacitor, that will be my next attempt, I'm not setup for SMD work so this will be interesting!  

Now I understand why the board is cheaper than buying a sensor on its own, I will learn from this mistake!

**Comment by EvoSparqz** [comment]
> > @flisboac I got a prompt response, very similar to @patryk02, so I dusted off the scope and although I could not produce a waveform to suggest such, there is a min/max voltage recorded and indeed the 1.8V supply line drops to 1.57V which is enough to reset the sensor. I'll see if I can tag on an additional ceramic capacitor, either the existing one is not large enough or is faulty.
> 
> But somehow I use the same sensor breakout with arduino library, it works without giving me 0 readings in regular opmode

Perhaps the Arduino library resets the sensor when the validity flag is lowered?  What evaluation board are you using?

**Comment by flisboac** [comment]
@EvoSparqz I guess all you need is to just increase capacitance just enough. I don't think the type of capacitor plays an important role here (apart from values and tolerances, perhaps; tantalum caps are less susceptible to capacitance variations due to voltage or temperature fluctuations). Tantalum capacitor was all I had in hand, but I expect ceramic capacitors to work too.

BTW, my ENS160 is working great so far! It reached Operation OK status in about an hour. I also found out that the 4.0V voltage in the 3.3V line is due to having too many I2C devices in the same bus, each of them bringing their own pull-up resistor (or at least I think that's why...). For some, I can remove the pull-up easily, but for this specific ENS160+AHT20, I cannot. Which is another negative point.

**Comment by flisboac** [comment]
Also, perhaps the module is cheap because of scale. For a Chinese factory, entirely optimized for production, the price may make sense. But by being so focused on price, quality may suffer, too. Not only that, the need for the module to "just work" brings about its own set of assumptions, and therefore problems,  depending on your scenario.

But I admit it's a bit sad how expensive those sensors are. Not only that, sourcing them may be a bit difficult too. I wish I could design my own board + daughterboards one day, with all the sensors I need, without having to pay a kidney for it.

**Comment by EvoSparqz** [comment]
Hey @flisboac, thank you for your comments :) I think this ENS160+AHT2x dev/eval board is just a really bad design, and they are being sold below cost to make some money back on a disaster :D A few too many comments about how the board heats up and affects the AHT2x sensor - but that doesn't concern me as I can use another sensor elsewhere, still cheaper to buy this board and not use the ATH2x sensor.  I just need to take a brave pill and remove the existing ceramic SMD and install a larger ceramic or indeed tantalum cap.

**Comment by AMoo-Miki** [comment]
In my case, I have two different ESP32s with different layouts. I built and flashed the exact same code on them. On one, ENS160+AHT2x starts with zeros and within a few seconds, it shows good numbers, but on the other, using the same ENS160+AHT2x, it constantly shows zeros. If I add any other device to the setup that worked, that one too shows only zeros. This behavior can be explained by the reasoning provided by @patryk02.

That said, I am not sure where I need to add the capacitor and would appreciate any help.

**Comment by 00svd00** [comment]
Really ugly solution, but adding 47uf capacitor to 1v8 perfectly fixed this issue for me
https://imgur.com/a/85QBtnk

**Comment by EvoSparqz** [comment]
> Really ugly solution, but adding 47uf capacitor to 1v8 perfectly fixed this issue for me https://imgur.com/a/85QBtnk

oh wow, and I thought my (failed) hack at stacking SMDs was below average.  I haven't managed to find an SMD big enough yet to bridge the power sag on the 1.8v rail... guess I might have to up my game and try something closer to 47uF!

**Comment by terryuland** [comment]
> Really ugly solution, but adding 47uf capacitor to 1v8 perfectly fixed this issue for me https://imgur.com/a/85QBtnk

Did the same with a 100uF and that fixed it immediately, thanks!

**Comment by webseitz** [comment]
The board featuring the AHT2x temperature and relative humidity sensor is known to have issues here and then. Breadboard setups in general with jumper wires show some more transition resistance than soldered solutions, this might lead to a voltage drop when setting the sensor to standard mode and hotplates are fired. If such a problem is present, one can read the firmware version but sensor signals are 0 or 1. Adding an extra capacitor to VCC close to the sensor will solve this issue.

**Comment by webseitz** [comment]
> My ENS160 is still running on "Initial Startup."
> 
> @patryk02 not necessarily regarding this issue, but I have some questions regarding the ENS160, I'd be glad if you could answer any of them:
> 
> 1. Is there any way to force ENS160 to run an "Initial Start-up" again?
> 2. Does the IC stop measuring until the data registers are read? If so, what if I read only some of them, would it still trigger a new measurement?
> 3. Is there any way to change the rate at which measurements are taken, when in STANDARD or CUSTOM mode? (From the "Immediate response time," I suppose it takes a measurement at least once a second, but I'm not sure)

1. No. Successful initial start-up is saved to non-volatile memory (NVM), which cannot be erased by customer. Please note that the sensor writes to NVM in 24 h intervals. Any information is lost if the sensor is reset, set to idle, or powered off before the 24 h period is over.
2. The sensor measures in standard mode every second regardless if the registers are read or not. Once new data is available the NEWDAT-bit is set to 1. If the data was read, this bit will be set to 0. Details can be found in the datasheet (register DEVICE_STATUS).
3. In standard mode the sampling rate is typically 1008 ms.
