### ISSUE TITLE
Aqi500?

### ISSUE THREAD

**Issue by tyeth** [sciosense/ENS160_driver#9]
There is a function to retrieve AQI500, but I'm at a loss as to what it refers to, and the old datasheet I have doesn't mention it.

The code indicates it's only for hardware revisions greater than zero: https://github.com/sciosense/ENS160_driver/blob/master/src/ScioSense_ENS160.cpp#L290

Can the code be documented, and the latest datasheet supplied?
This was my reference:
https://www.sciosense.com/wp-content/uploads/documents/SC-001224-DS-9-ENS160-Datasheet.pdf

**Comment by proostas** [comment]
I guess it can only be used with ENS161. With ENS160 it will always report 0. So it seems ENS160 can only report AQI-UBA values.

**Comment by webseitz** [comment]
ScioSense Airquality Index AQIS (value 0 to 500) is only available with the ENS161.
